version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - yarn install
  build:
    commands:
      - yarn deploy blue-green-api-stack -c environment=dev --require-approval never
