version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - yarn install
  build:
    commands:
      - npx cdk deploy '*' -c environment=dev --require-approval never
